<?php

namespace AppBundle\Repository;

/**
 * MunicipalityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MunicipalityRepository extends \Doctrine\ORM\EntityRepository
{
}
